FROM mambaorg/micromamba:2.0.3 as micromamba

FROM nvcr.io/nvidia/ai-workbench/python-cuda120:1.0.3

USER root

RUN apt-get update -y && apt-get -y upgrade

ARG MAMBA_USER=lfi
ARG MAMBA_USER_ID=22367
ARG MAMBA_USER_GID=22367
ENV MAMBA_USER=$MAMBA_USER
ENV MAMBA_ROOT_PREFIX="/opt/conda"
ENV MAMBA_EXE="/bin/micromamba"

COPY --from=micromamba "$MAMBA_EXE" "$MAMBA_EXE"
COPY --from=micromamba /usr/local/bin/_activate_current_env.sh /usr/local/bin/_activate_current_env.sh
COPY --from=micromamba /usr/local/bin/_dockerfile_shell.sh /usr/local/bin/_dockerfile_shell.sh
COPY --from=micromamba /usr/local/bin/_entrypoint.sh /usr/local/bin/_entrypoint.sh
COPY --from=micromamba /usr/local/bin/_dockerfile_initialize_user_accounts.sh /usr/local/bin/_dockerfile_initialize_user_accounts.sh
COPY --from=micromamba /usr/local/bin/_dockerfile_setup_root_prefix.sh /usr/local/bin/_dockerfile_setup_root_prefix.sh

RUN /usr/local/bin/_dockerfile_initialize_user_accounts.sh && \
    /usr/local/bin/_dockerfile_setup_root_prefix.sh

SHELL ["/usr/local/bin/_dockerfile_shell.sh"]

ENTRYPOINT ["/usr/local/bin/_entrypoint.sh"]

USER $MAMBA_USER

COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

COPY ./env_docker.yml /home/$MAMBA_USER/env_docker.yml
COPY ./requirements.txt /home/$MAMBA_USER/requirements.txt

CMD ["/bin/bash"]

RUN micromamba env create -vv --yes --file /home/$MAMBA_USER/env_docker.yml && \
micromamba run -n dev micromamba clean --all --yes

WORKDIR /home/$MAMBA_USER/mnt/dev

RUN micromamba run -n dev uv pip install -r /home/$MAMBA_USER/requirements.txt

RUN rm -rf ~/.cache

RUN echo "micromamba activate dev" >> ~/.bashrc