[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"

[project]
name ="src"
version = "0.0.1"
dependencies = []

[tool.maturin]
features = ["pyo3/extension-module"]
module-name = "src.rust_modules"
python-source = "./"
rust-source = "./rust"
