model_version: 0.1
seed: 69420
base_model: Rostlab/prot_t5_xl_uniref50
# base_model: facebook/esm2_t6_8M_UR50D
training_config:
  learning_rate: 1e-4
  batch_size: 2
  num_epochs: 10
  logging_steps: 1
  eval_steps: 300
  save_steps: 9999999
