[project]
name = "protfold"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Finn Lueth", email = "finn@lueth.net" }
]
requires-python = ">=3.12"
dependencies = []

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
