mdcath_subset:
  temperatures: 
    - "320"
    - "348"
  replicas: 
    - "0"
    - "1"
mdcath_all:
  temperatures: 
    - "320"
    - "348"
    - "379"
    - "413"
    - "450"
  replicas: 
    - "0"
    - "1"
    - "2"
    - "3"
    - "4"